# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.88"
  # config.vm.network "public_network"

  # config.ssh.forward_agent = true

  config.vm.synced_folder "./", "/vagrant"

  config.vm.provision :shell, :inline => <<-EOT
    # Add remi-php55 repository
    rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    # Install packages
    yum -y install gcc make git
    yum -y install mysql-server --enablerepo=remi
    yum -y install php php-devel pcre-devel php-mysql httpd --enablerepo=remi-php55
    # Build and install Phalcon
    cd /tmp
    git clone --depth=1 git://github.com/phalcon/cphalcon.git
    cd cphalcon/build
    ./install
    sh -c "echo 'extension=phalcon.so' > /etc/php.d/phalcon.ini"
    # Apache setting
    cp -a /vagrant/provision/httpd.conf /etc/httpd/conf/httpd.conf
    chkconfig httpd on
    service httpd restart
    # MySQL setting
    chkconfig mysqld on
    service mysqld restart
    mysql -u root -e 'CREATE DATABASE reading_list'
    # PHP setting
    cp -a /vagrant/provision/php.ini /etc/php.ini
    # Install composer
    cd /tmp
    curl -sS https://getcomposer.org/installer | php    
    mv composer.phar /usr/local/bin/composer
    # Install Phalcon DevTools
    mkdir /home/vagrant/bin
    cd /home/vagrant/bin
    /usr/local/bin/composer require phalcon/devtools dev-master 
    chown -R vagrant /home/vagrant
    ln -s /home/vagrant/bin/vendor/bin/phalcon.php /usr/local/bin/phalcon
    # Document root setting
    chown vagrant /var/www/html
    echo '<?php phpinfo();' > /var/www/html/info.php
  EOT
end
